#!/usr/bin/env python3
"""Generate ROM-derived gameplay object picture tables for Defender.

This extracts the red-label object descriptors and their primary picture bytes
from `defb6.src`, then writes them as a Rust module so the runtime no longer
needs to load cropped gameplay PNGs for those objects.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = Path("/tmp/defender-src/src/defb6.src")
OUTPUT_PATH = ROOT / "src" / "object_rom_data.rs"

PICTURE_LABELS = [
    "PLAPIC",
    "PLBPIC",
    "PLAMIN",
    "LASP1",
    "BMBP1",
    "BMBP2",
    "ASTP1",
    "ASTP2",
    "ASTP3",
    "ASTP4",
    "TIEP1",
    "TIEP2",
    "TIEP3",
    "TIEP4",
    "SCZP1",
    "PRBP1",
    "SWPIC1",
    "LNDP1",
    "LNDP2",
    "LNDP3",
    "UFOP1",
    "UFOP2",
    "UFOP3",
    "BXPIC",
    "SWXP1",
    "C25P1",
    "C5P1",
]


def split_payload(payload: str) -> list[str]:
    return [part.strip().split()[0] for part in payload.split(",") if part.strip()]


def parse_source() -> dict[str, list[tuple[str, list[str]]]]:
    records: dict[str, list[tuple[str, list[str]]]] = {}
    current_label: str | None = None

    for raw_line in SOURCE_PATH.read_text().splitlines():
        line = raw_line.split(";", 1)[0].rstrip()
        if not line.strip():
            current_label = None
            continue

        entry = re.match(r"^([A-Z0-9]+)\s+(FCB|FDB)\s+(.*)$", line)
        if entry:
            label, directive, payload = entry.groups()
            current_label = label
            records.setdefault(label, []).append((directive, split_payload(payload)))
            continue

        continuation = re.match(r"^\s+(FCB|FDB)\s+(.*)$", line)
        if continuation and current_label is not None:
            directive, payload = continuation.groups()
            records[current_label].append((directive, split_payload(payload)))
            continue

        current_label = None

    return records


def token_to_int(token: str) -> int:
    if token.startswith("$"):
        return int(token[1:], 16)
    return int(token, 10)


def token_bytes(token: str, directive: str) -> list[int]:
    value = token_to_int(token)
    if directive == "FCB":
        return [value & 0xFF]
    return [(value >> 8) & 0xFF, value & 0xFF]


def collect_bytes(records: dict[str, list[tuple[str, list[str]]]], label: str, expected: int) -> list[int]:
    data = records.get(label)
    if data is None:
        raise RuntimeError(f"missing data label {label} in {SOURCE_PATH}")

    bytes_out: list[int] = []
    for directive, tokens in data:
        for token in tokens:
            bytes_out.extend(token_bytes(token, directive))
            if len(bytes_out) >= expected:
                return bytes_out[:expected]

    raise RuntimeError(f"label {label} only produced {len(bytes_out)} bytes, expected {expected}")


def parse_picture(records: dict[str, list[tuple[str, list[str]]]], label: str) -> tuple[int, int, list[int]]:
    picture = records.get(label)
    if picture is None:
        raise RuntimeError(f"missing descriptor {label} in {SOURCE_PATH}")
    if len(picture) < 2 or picture[0][0] != "FCB" or picture[1][0] != "FDB":
        raise RuntimeError(f"descriptor {label} is not in the expected format")

    rows, bytes_per_row = [token_to_int(value) for value in picture[0][1][:2]]
    primary_data_label = picture[1][1][0]
    total_bytes = rows * bytes_per_row
    return rows, bytes_per_row, collect_bytes(records, primary_data_label, total_bytes)


def rust_array(name: str, values: list[int]) -> str:
    lines = [f"pub const {name}: [u8; {len(values)}] = ["]
    for offset in range(0, len(values), 12):
        chunk = ", ".join(f"0x{value:02X}" for value in values[offset : offset + 12])
        lines.append(f"    {chunk},")
    lines.append("];")
    return "\n".join(lines)


def rust_picture(name: str, rows: int, bytes_per_row: int) -> str:
    return (
        f"pub const {name}: RomPictureData = RomPictureData {{ "
        f"rows: {rows}, bytes_per_row: {bytes_per_row}, bytes: &{name}_BYTES }};"
    )


def main() -> None:
    records = parse_source()

    content = [
        "// Generated by tools/extract_rom_object_data.py from /tmp/defender-src/src/defb6.src.",
        "",
        "#[derive(Clone, Copy, Debug)]",
        "pub struct RomPictureData {",
        "    pub rows: u8,",
        "    pub bytes_per_row: u8,",
        "    pub bytes: &'static [u8],",
        "}",
        "",
        rust_array("CRTAB", collect_bytes(records, "CRTAB", 16)),
        "",
        rust_array("TCTAB", collect_bytes(records, "TCTAB", 9)),
        "",
    ]

    for label in PICTURE_LABELS:
        rows, bytes_per_row, data = parse_picture(records, label)
        content.append(rust_array(f"{label}_BYTES", data))
        content.append("")
        content.append(rust_picture(label, rows, bytes_per_row))
        content.append("")

    OUTPUT_PATH.write_text("\n".join(content))
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
