#!/usr/bin/env python3
"""Generate ROM-derived attract data tables for Defender.

This extracts the raw `LGOTAB` and `DEFDAT` tables from the red-label
`amode1.src` source drop and writes them as a Rust module that runtime code can
decode without requiring a local ROM/source tree.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AMODE_PATH = Path("/tmp/defender-src/src/amode1.src")
OUTPUT_PATH = ROOT / "src" / "attract_rom_data.rs"

SYMBOLS = {
    "NULL": 0xFF,
    "HYPERC": 0xFE,
    "QUIT": 0xFD,
}


def parse_fcb_table(lines: list[str], start_label: str, end_label: str) -> list[int]:
    start = None
    values: list[int] = []

    for index, line in enumerate(lines):
        label = line.split()[0] if line.split() else ""
        if label == start_label:
            start = index
        elif start is not None and label == end_label:
            break

        if start is None or "FCB" not in line:
            continue

        payload = line.split("FCB", 1)[1]
        for part in payload.split(","):
            token = part.strip().split()[0]
            if not token:
                continue
            if token in SYMBOLS:
                values.append(SYMBOLS[token])
            elif token.startswith("$"):
                values.append(int(token[1:], 16))

    if start is None:
        raise RuntimeError(f"table {start_label} not found in {AMODE_PATH}")
    return values


def format_rust_array(name: str, values: list[int]) -> str:
    lines = [f"pub const {name}: [u8; {len(values)}] = ["]
    for offset in range(0, len(values), 12):
        chunk = ", ".join(f"0x{value:02X}" for value in values[offset : offset + 12])
        lines.append(f"    {chunk},")
    lines.append("];")
    return "\n".join(lines)


def main() -> None:
    lines = AMODE_PATH.read_text().splitlines()
    williams = parse_fcb_table(lines, "LGOTAB", "DEFDAT")
    defender = parse_fcb_table(lines, "DEFDAT", "DEFDEN")

    content = [
        "// Generated by tools/extract_rom_attract_data.py from /tmp/defender-src/src/amode1.src.",
        "",
        format_rust_array("WILLIAMS_TRACE_DATA", williams),
        "",
        format_rust_array("DEFENDER_LOGO_DATA", defender),
        "",
    ]

    OUTPUT_PATH.write_text("\n".join(content))
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
